"""add_system_config_and_admin

Revision ID: b1fa24cb073f
Revises: d8d4e2ccb5cd
Create Date: 2026-01-11 12:45:15.328055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1fa24cb073f'
down_revision: Union[str, Sequence[str], None] = 'd8d4e2ccb5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_config_key'), 'system_config', ['key'], unique=False)
    op.drop_index(op.f('ix_global_config_id'), table_name='global_config')
    op.drop_index(op.f('ix_global_config_key'), table_name='global_config')
    op.drop_table('global_config')
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_user_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_user_id_fkey'), 'messages', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'])
    op.create_table('global_config',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('global_config_pkey'))
    )
    op.create_index(op.f('ix_global_config_key'), 'global_config', ['key'], unique=True)
    op.create_index(op.f('ix_global_config_id'), 'global_config', ['id'], unique=False)
    op.drop_index(op.f('ix_system_config_key'), table_name='system_config')
    op.drop_table('system_config')
    # ### end Alembic commands ###
